# Generated by Django 4.0 on 2021-12-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0003_author_headshot_book_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
