# Generated by Django 4.0 on 2021-12-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
